### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by aanderse** [kodi-game/controller-topology-project#110]
Could you please tag a release when you get a chance? Thank you!

**Comment by garbear** [comment]
Amazing, I'm just discovering an issue I missed two years ago. Yes, we should version this repo. What better time to tag `v1.0.0`.

I chose to use Python packaging to manage versioning: https://github.com/kodi-game/controller-topology-project/pull/304

**Comment by aanderse** [comment]
thanks so much!
