### ISSUE TITLE
Addon Summary "game.controller.ps.mouse" and "game.controller.snes.mouse" are propagated on Weblate

### ISSUE THREAD

**Issue by olavinto** [kodi-game/controller-topology-project#155]
At Weblate the "Addon Summary" stings of the "game.controller.ps.mouse" and "game.controller.snes.mouse" addons are propagated which makes it impossible to translate one of them correctly since one of them is always replaced. So we end up with either "PlayStation mouse" or "SNES mouse" in both of them.

**Comment by gade01** [comment]
@olavinto 
Thanks for bringing this to our attention.
I can see game.conroller.ps.mouse and game.controller.snes.mouse has the exact same addon summary in addon.xml

I created a PR to fix this: https://github.com/kodi-game/controller-topology-project/pull/156

**Comment by gade01** [comment]
@olavinto Can you please check that everything looks correctly at Weblate now?
Thanks.

**Comment by olavinto** [comment]
Yep, seems to be fine now, thank you. 👍

**Comment by gade01** [comment]
Sounds great, thanks.
