### ISSUE TITLE
Controllers not working with PSX emulators

### ISSUE THREAD

**Issue by xplodwild** [kodi-game/controller-topology-project#6]
Hey there,

For some reason, the PSX controllers are not working for me. When playing a GBA game, I get the GBA feature properly:
```
DEBUG: Feature [ down ] on game.controller.gba pressed
DEBUG: Feature [ down ] on game.controller.gba released
```

However, when playing a PlayStation game, the input seems to use Kodi's features (game.controller.default) instead of game.controller.ps:
```
19:48:04.798 T:140033625409280   DEBUG: Feature [ down ] on game.controller.default pressed
19:48:04.902 T:140033625409280   DEBUG: Feature [ down ] on game.controller.default released
```

I'm not sure where to look to find the faulty piece of code. The problem seems to happen both with PCSX and Mednafen PSX emulators, and happens with 2 different controllers, so it seems generally linked to `game.controller.ps`. What part of the code decides which feature to use?

Thanks!

**Comment by garbear** [comment]
The joystick handling system is pretty complex, but there's a single point where all button presses pass through: https://github.com/xbmc/xbmc/blob/master/xbmc/peripherals/devices/PeripheralJoystick.cpp#L170. I always start by setting a breakpoint there and then following the press to see why it's handled the way it is. Good luck! If you get stuck I can help you look into this.

**Comment by garbear** [comment]
New controller system has been added. Is this still an issue?

**Comment by garbear** [comment]
Closing due to no response. Please re-open if this is still an issue!
